export const PLANS = [
  {
    id: 'PRESENCE',
    name: 'Presence',
    tagline: 'Your brand’s social, run by agents',
    priceMonthly: 99,
    audience: 'individual',
    features: ['1–2 networks', 'Draft approvals', 'Weekly pulse', 'Mobile command'],
    leadGen: false,
    multiClient: false,
    maxClientSeats: 1,
  },
  {
    id: 'PIPELINE',
    name: 'Pipeline',
    tagline: 'Social + lead generation',
    priceMonthly: 249,
    audience: 'individual_leads',
    features: ['Everything in Presence', 'Outreach drafts', 'Lead inbox', 'Monthly note'],
    leadGen: true,
    multiClient: false,
    maxClientSeats: 1,
  },
  {
    id: 'AGENCY',
    name: 'Agency',
    tagline: 'Reseller dashboard for your clients',
    priceMonthly: 499,
    audience: 'reseller',
    features: ['Sub-accounts', 'Team seats', 'White-label domain', 'Cross-client activity'],
    leadGen: true,
    multiClient: true,
    maxClientSeats: 25,
  },
] as const
